services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    MateuszBieniek\IbexaDxpRedisToolsBundle\Command\RedisCheckerCommand:
        tags:
            - { name: console.command }

    MateuszBieniek\IbexaDxpRedisToolsBundle\Command\RedisContentCheckerCommand:
        tags:
            - { name: console.command }

    MateuszBieniek\IbexaDxpRedisTools\Redis\Gateway\Factory\RedisGatewayFactory: ~

    MateuszBieniek\IbexaDxpRedisTools\Redis\Gateway\Factory\RedisGatewayFactoryInterface: '@MateuszBieniek\IbexaDxpRedisTools\Redis\Gateway\Factory\RedisGatewayFactory'
